---
# yamllint disable rule:line-length
name: Build
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'server/**'
            - .github/workflows/push-to-repository.yml
jobs:
    pip-install-and-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9]
        env:
            DB_DATABASE: camcops
            DB_CAMCOPS_USER: camcops
            DB_CAMCOPS_PASSWORD: camcops
            DB_ROOT_USER: root
            DB_ROOT_PASSWORD: root

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up MySQL
              run: |
                  set -xe
                  sudo /etc/init.d/mysql start
                  mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_ROOT_USER  }} -p${{ env.DB_ROOT_PASSWORD }}
                  mysql -e 'CREATE USER `${{ env.DB_CAMCOPS_USER }}`@`localhost` IDENTIFIED BY "${{ env.DB_CAMCOPS_PASSWORD }}";' -u${{ env.DB_ROOT_USER  }} -p${{ env.DB_ROOT_PASSWORD }}
                  mysql -e 'GRANT ALL PRIVILEGES ON `${{ env.DB_DATABASE }}`.* TO `${{ env.DB_CAMCOPS_USER }}`@`localhost`;' -u${{ env.DB_ROOT_USER  }} -p${{ env.DB_ROOT_PASSWORD }}
            - name: Pip install and tests
              run: |
                  set -xe
                  # Install wkhtmltopdf on headless ubuntu 18 vps
                  # https://gist.github.com/lobermann/ca0e7bb2558b3b08923c6ae2c37a26ce
                  # 429 = Too many requests. Unfortunately wget doesn't read the
                  # Retry-after header so just wait 5 minutes
                  wget --retry-on-http-error=429 --waitretry=300 --tries=20 https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
                  sudo apt-get -y install fontconfig libxrender1 xfonts-75dpi xfonts-base
                  sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
                  python -m venv ${HOME}/venv
                  source ${HOME}/venv/bin/activate
                  python -VV
                  python -m site
                  python -m pip install -U pip
                  echo dumping pre-installed packages
                  python -m pip freeze
                  echo installing pip packages
                  python -m pip install -e server/.
                  echo checking packages for conflicts
                  python -m pip check
                  echo installing vulnerability checker
                  python -m pip install safety
                  echo checking packages for vulnerabilities
                  safety check --full-report
                  echo checking python for style and errors
                  flake8 --config=setup.cfg server/camcops_server
                  export CAMCOPS_CONFIG_FILE="${HOME}/camcops.cfg"
                  camcops_server demo_camcops_config | sed 's/YYY_USERNAME_REPLACE_ME/${{ env.DB_CAMCOPS_USER }}/g' | sed 's/ZZZ_PASSWORD_REPLACE_ME/${{ env.DB_CAMCOPS_PASSWORD }}/g' > "${CAMCOPS_CONFIG_FILE}"
                  echo running tests
                  cd server/camcops_server
                  pytest -v
                  echo testing database upgrade / downgrade
                  python -m pip install pymysql
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE} --show_sql_only
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE}
                  # WARNING: Current Alembic v1.0.0 bug in downgrading with as_sql=True; may fail
                  # camcops_server dev_downgrade_db --config ${CAMCOPS_CONFIG_FILE} --destination_db_revision 0001 --confirm_downgrade_db --show_sql_only
                  camcops_server dev_downgrade_db --config ${CAMCOPS_CONFIG_FILE} --destination_db_revision 0001 --confirm_downgrade_db
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE} --show_sql_only
                  camcops_server upgrade_db --config ${CAMCOPS_CONFIG_FILE}

    build-and-install-package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Build and install debian package
              run: |
                  set -xe
                  sudo apt-get -y install alien fakeroot lintian gdebi
                  # 429 = Too many requests. Unfortunately wget doesn't read the
                  # Retry-after header so just wait 5 minutes
                  wget --retry-on-http-error=429 --waitretry=300 --tries=20 https://downloads.sourceforge.net/project/rpmrebuild/rpmrebuild/2.15/rpmrebuild-2.15-1.noarch.rpm
                  fakeroot alien --to-deb rpmrebuild-2.15-1.noarch.rpm
                  sudo dpkg -i rpmrebuild_2.15-2_all.deb
                  python -m venv ${HOME}/venv
                  source ${HOME}/venv/bin/activate
                  python -VV
                  python -m site
                  python -m pip install -U pip
                  echo dumping pre-installed packages
                  python -m pip freeze
                  echo installing pip packages
                  python -m pip install -e server/.
                  echo building packages
                  server/tools/MAKE_LINUX_PACKAGES.py
                  echo installing debian package
                  server/tools/REINSTALL_DEBIAN_PACKAGE.sh
                  echo checking packages for conflicts
                  /usr/share/camcops/venv/bin/pip check
